name: Windows RDP with Action
on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Session duration in minutes'
        required: true
        default: '60'
        type: number

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: ${{ github.event.inputs.duration }}
    
    steps:
      - name: Setup RDP environment
        uses: nya-misty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: "P@ssw0rd123!"
